In [20]:
from datetime import datetime
data_ora_correnti = datetime.now()
data_ora_formattate = data_ora_correnti.strftime("%Y-%m-%d %H:%M:%S")
autore = 'Federico Targa'
print('------------------------------------')
print("| Data e ora:", data_ora_formattate,'|')
print('------------------------------------')
print('------------------------------------')
print('     |Autore: ', autore                 ,'|')
print('------------------------------------')

------------------------------------
| Data e ora: 2023-06-11 10:17:56 |
------------------------------------
------------------------------------
     |Autore:  Federico Targa |
------------------------------------


--------------------------------------------------------------------------------------------------------------------------------

ABSTRACT

Il merge sort è un algoritmo di ordinamento basato su confronti che utilizza un processo di risoluzione ricorsivo, sfruttando la tecnica del Divide et Impera, che consiste nella suddivisione del problema in sottoproblemi della stessa natura di dimensione via via più piccola. Fu inventato da John von Neumann nel 1945. Una descrizione dettagliata e un'analisi della versione bottom-up dell'algoritmo apparve in un articolo di Goldstine e Neumann già nel 1948.

--------------------------------------------------------------------------------------------------------------------------------

Concettualmente, l'algoritmo funziona nel seguente modo:

se la sequenza da ordinare ha lunghezza 0 oppure 1, è già ordinata. Se, invece, e la lunghezza è maggiore di 1 , la sequenza viene divisa (divide) in due metà (se la sequenza contiene un numero dispari di elementi, viene divisa in due sottosequenze di cui la prima ha un elemento in più della seconda).Ognuna di queste sottosequenze viene ordinata, applicando ricorsivamente l'algoritmo (impera).
Le due sottosequenze ordinate vengono fuse (combina). Per fare questo, si estrae ripetutamente il minimo delle due sottosequenze e lo si pone nella sequenza in uscita, che risulterà ordinata.

--------------------------------------------------------------------------------------------------------------------------------

Riassumendo, possiamo quindi dire che, l'algoritmo Merge Sort, si compone di 3 steps:

1) Dividi: l'algoritmo divide la lista non ordinata a metà, ricorsivamente, fino a quando non rimangono singoli elementi o liste vuote; 

2) Conquista: una volta che la lista viene suddivisa in singoli elementi o liste vuote, non è necessario alcun ulteriore ordinamento; 


3) Combina: l'algoritmo combina le due liste ordinate (ottenute dalla fase di conquista) in una singola lista ordinata. Questa fase richiede la comparazione degli elementi delle due liste e l'inserimento degli elementi nella lista di output in modo appropriato.

________________________________________________________________________________________________________________________________

Vediamo un esempio

Supponendo di dover ordinare la sequenza [10 3 15 2 1 4 9 0], l'algoritmo procede ricorsivamente dividendola in metà successive, fino ad arrivare agli elementi:

[10] [3] [15] [2] [1] [4] [9] [0]

A questo punto si fondono (merge) in maniera ordinata gli elementi, riunendoli in coppie:

[3 10] [2 15] [1 4] [0 9]

Al passo successivo, si fondono le coppie di array di due elementi:

[2 3 10 15] [0 1 4 9]

Infine, fondendo le due sequenze di quattro elementi, si ottiene la sequenza ordinata:

[0 1 2 3 4 9 10 15]

L'esecuzione ricorsiva all'interno del calcolatore non avviene nell'ordine descritto sopra. Tuttavia, si è formulato l'esempio in questo modo per renderlo più comprensibile.

La valutazione del tempo di esecuzione dell'algoritmo Merge Sort può essere analizzata nel seguente modo:

Dividi: La fase di divisione dell'algoritmo Merge Sort richiede un tempo costante, poiché coinvolge solo operazioni di      suddivisione dell'input in due parti. Quindi, il tempo richiesto per questa fase è O(1).

Conquista: Poiché la fase di conquista viene eseguita quando la lista viene divisa in singoli elementi o liste vuote, non è richiesta alcuna operazione di ordinamento. Pertanto, il tempo richiesto per questa fase è anche O(1).

Combina: La fase di combinazione è la parte cruciale dell'algoritmo Merge Sort. Durante questa fase, vengono combinate le liste ordinate ottenute dalla fase di conquista. La combinazione richiede la comparazione degli elementi delle due liste e l'inserimento degli elementi nella lista di output in modo appropriato. Il tempo richiesto per la combinazione dipende dalla dimensione delle liste da combinare.

--------------------------------------------------------------------------------------------------------------------------------

Nel caso migliore, quando le due liste da combinare hanno dimensioni simili, la combinazione richiede un tempo lineare. Ad esempio, se le due liste hanno entrambe "n/2" elementi, il tempo richiesto per la combinazione sarà O(n), dove "n" è la dimensione totale dell'input.

Nel caso peggiore, quando una delle due liste è molto più grande dell'altra, la combinazione richiede un tempo proporzionale alla dimensione della lista più grande. Pertanto, il tempo richiesto per la combinazione nel caso peggiore è ancora O(n), dove "n" è la dimensione totale dell'input.

--------------------------------------------------------------------------------------------------------------------------------

Passiamo ora all'implementazione dell'algoritmo attraverso Python

--------------------------------------------------------------------------------------------------------------------------------

In [21]:
'''
import numpy as np

# Genera un array casuale di numeri interi senza duplicati
arr = np.random.choice(range(1, 100), size=10, replace = False) # replace = True => posso avere duplicati
print(arr)
'''

'\nimport numpy as np\n\n# Genera un array casuale di numeri interi senza duplicati\narr = np.random.choice(range(1, 100), size=10, replace = False) # replace = True => posso avere duplicati\nprint(arr)\n'

In [22]:
import numpy as np

# Impostiamo il seed del generatore di numeri casuali a un valore specifico
# seed ci permette di ottenere sempre gli stessi valori randomici 
#ogni volta che mando in run il programma
np.random.seed(42)

# Genera un array casuale di dimensione 10 con valori compresi tra 1 e 199
arr = np.random.randint(1, 200, size = 15)

print(arr)

[103 180  93  15 107  72 189  21 103 122  75  88 117 100 104]


In [23]:
# Innanzitutto, se il vettore in input è unitario o vuoto, il vettore è già "ordinato"
def merge_sort(arr):
    if len(arr) <= 1:
        return arr
# se, invece, len(arr) > 1, innanzitutto prepariamo i due sub-arrays destro e sinistro
    mid = len(arr) // 2 # usiamo la differenza senza resto // così evitiamo problemi in caso di liste dispari
    left_half = arr[:mid]
    right_half = arr[mid:]
    
#Dopodichè,richiamiamo ricorsivamente merge_sort per le due metà e combiniamo le due metà già ordinate
    left_half = merge_sort(left_half)
    right_half = merge_sort(right_half)

    return merge(left_half, right_half)

In [24]:
# ora, definiamo una funzione di merging (fusione, unione...) delle due sottosequenze ordinate
def merge(left, right):
    merged = []
    i = 0  # Indice per la lista left
    j = 0  # Indice per la lista right

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            merged.append(left[i])
            i += 1
        else:
            merged.append(right[j])
            j += 1
    merged.extend(left[i:])
    merged.extend(right[j:])

    return merged

--------------------------------------------------------------------------------------------------------------------------------

Testiamo il funzionamento

In [25]:
user = input('Vuoi ordinare in modo crescente (C) o decrescente (D)? ')
if user == 'C':
    sorted_arr = merge_sort(arr)
    print('Il tuo array ordinato in modo crescente è: ', sorted_arr)
else:
    sorted_arr = merge_sort(arr)
    print('Il tuo array ordinato in modo crescente è: ', sorted_arr[::-1])

Vuoi ordinare in modo crescente (C) o decrescente (D)? C
Il tuo array ordinato in modo crescente è:  [15, 21, 72, 75, 88, 93, 100, 103, 103, 104, 107, 117, 122, 180, 189]


In [26]:
user = input('Vuoi ordinare in modo crescente (C) o decrescente (D)? ')
if user == 'C':
    sorted_arr = merge_sort(arr)
    print('Il tuo array ordinato in modo crescente è: ', sorted_arr)
else:
    sorted_arr = merge_sort(arr)
    print('Il tuo array ordinato in modo decresente è: ', sorted_arr[::-1])

Vuoi ordinare in modo crescente (C) o decrescente (D)? D
Il tuo array ordinato in modo decresente è:  [189, 180, 122, 117, 107, 104, 103, 103, 100, 93, 88, 75, 72, 21, 15]


OSS: la cella sopra può essere eliminata, in quanto usata solamente per testare l'ordinamento decrescente in un un unico run!